<a href="https://colab.research.google.com/github/faeezeh/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Let's Go start

useful link 
https://numpy.org/doc/stable/




*   shift+tab -----> to see documentation
*   shift+tab+tab -----> to see more details




In [2]:
pip install numpy 

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
pip install numpy --upgarde


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --upgarde


In [4]:
import numpy as np

In NumPy, an ndarray (short for "n-dimensional array") is a multidimensional container of items of the same type and size. It provides a fast, efficient way of storing and manipulating large arrays of homogeneous data (i.e., data of the same type).



*   scalar (0_D array)
*   vector (1_D array)
*   matrix (2-D array)



In [8]:
array_a = np.array([1])
print("0_D array :",array_a)

array_b = np.array([1,2,3])
print("1_D array :",array_b)

array_c = np.array([[1,2,3],[4,5,6]])
print("2_D array :",array_c)


0_D array : [1]
1_D array : [1 2 3]
2_D array : [[1 2 3]
 [4 5 6]]


In [19]:
array_a.shape

(1,)

In [15]:
type(array_a)

numpy.ndarray

In [13]:
array_b.shape

(3,)

In [14]:
array_c.shape

(2, 3)

In [9]:
array_d = array_a + array_b + array_c

In [10]:
array_d

array([[ 3,  5,  7],
       [ 6,  8, 10]])

to see the number of rows

In [17]:
array_d.shape[0]

2

number of columns

In [18]:
array_d.shape[1]

3

In [20]:
array_e = np.array(5)
print(array_e)

5


In [21]:
array_e.shape

()

In [22]:
type(array_e)

numpy.ndarray

In [23]:
array_f = np.array([[[[[[[[13]]]]]]]])

In [24]:
print(array_f)

[[[[[[[[13]]]]]]]]


In [25]:
array_f.shape

(1, 1, 1, 1, 1, 1, 1, 1)

In [26]:
array_f.shape[0]

1

In [27]:
array_f.shape[1]

1

Array Vs List


list is in single line
while 
np.array is like table with row and column


array is element wise

In [28]:
list_a = [1,2,3,4,5,6]
print(list_a)
len(list_a)

[1, 2, 3, 4, 5, 6]


6

In [31]:
list_b = [[1,2,3],[4,5,6]]
print(list_b)
print(len(list_b))
type(list_b)

[[1, 2, 3], [4, 5, 6]]
2


list

In [37]:
len(list_b[0])

3

In [36]:
list_b[1]

[4, 5, 6]

In [33]:
array_g = np.array(list_b)
print(array_g)
print(array_g.shape)
type(array_g)

[[1 2 3]
 [4 5 6]]
(2, 3)


numpy.ndarray

In [38]:
list_c = list_b[0] + list_b[1]
list_c

[1, 2, 3, 4, 5, 6]

In [41]:
array_h = array_g[0]+array_g[1]
array_h

array([5, 7, 9])

In [45]:
import math
array_j = math.sqrt(array_g[1,0])
print(array_j)

2.0


In [44]:
print(array_g[1,0])

4
