<a href="https://colab.research.google.com/github/faeezeh/Numpy/blob/main/NumpyEx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy exercise**

1. Every categorical variable must be quantified

2. We need to change any text columns into numbers

3. Positive or negative connotation 

In [372]:
import numpy as np 

In [373]:
np.set_printoptions( suppress = True , linewidth = 100 , precision = 2 )

In [374]:
raw_data_np = np.genfromtxt("/content/sample_data/loan-data.csv",
                            delimiter=";",
                            skip_header=1,
                            autostrip=True,
                            encoding="cp855")
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [375]:
np.isnan(raw_data_np).sum()

88005

In [376]:
temp_mean =  np.nanmean(raw_data_np , axis=0)
temp_min =  np.nanmin(raw_data_np , axis=0)
temp_fill = np.nanmax(raw_data_np) + 1

<ipython-input-376-d8c71dda0048>:1: RuntimeWarning: Mean of empty slice
  temp_mean =  np.nanmean(raw_data_np , axis=0)
<ipython-input-376-d8c71dda0048>:2: RuntimeWarning: All-NaN slice encountered
  temp_min =  np.nanmin(raw_data_np , axis=0)


In [377]:
temp_min

array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
             nan,       nan,       nan,       nan,       nan,      0.  ])

In [378]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [379]:
temp_fill

68616520.0

In [380]:
temp_sets = np.array([temp_min,temp_mean,temp_fill])

<ipython-input-380-10f5c992cf5e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp_sets = np.array([temp_min,temp_mean,temp_fill])


In [381]:
temp_sets

array([array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
                    nan,       nan,       nan,       nan,       nan,      0.  ])                     ,
       array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
                   440.92,         nan,         nan,         nan,         nan,         nan,     3143.85]),
       68616520.0], dtype=object)

In [382]:
cols_string = np.argwhere(np.isnan(temp_mean)).squeeze()
cols_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [383]:
cols_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
cols_numeric

array([ 0,  2,  4,  6,  7, 13])

In [384]:
loan_data_string = np.genfromtxt("/content/sample_data/loan-data.csv",
                            delimiter=";",
                            skip_header=1,
                            autostrip=True,
                            usecols = cols_string,
                            encoding="cp855",
                            dtype = np.str)
loan_data_string

<ipython-input-384-72b7ab78f43f>:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [385]:
loan_data_num = np.genfromtxt("/content/sample_data/loan-data.csv",
                            delimiter=";",
                            skip_header=1,
                            autostrip=True,
                            usecols = cols_numeric,
                            encoding="cp855")
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,         nan,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,         nan,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,         nan,         nan,     2185.64],
       [46154151.  ,         nan,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,         nan,      309.97,      301.9 ]])

In [386]:
header = np.genfromtxt("/content/sample_data/loan-data.csv",
                             delimiter=";",
                            skip_footer=raw_data_np.shape[0],
                            autostrip=True,
                            encoding="cp855",
                            dtype = np.str)
header

<ipython-input-386-20add4c119f6>:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [387]:
str_header , num_header = header[cols_string],header[cols_numeric]

In [388]:
str_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [389]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [390]:
def checkpoint ( file_name , checkpoint_header , checkpoint_data):
  np.savez( file_name , header = checkpoint_header , data = checkpoint_data )
  checkpoint_variable = np.load( file_name + ".npz" )
  return(checkpoint_variable)

In [391]:
checkpoint_test = checkpoint("checkpoint_test",str_header, loan_data_string)

In [392]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [393]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [394]:
str_header[0] = "issue_date"

In [395]:
str_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

**issue_date**

In [396]:
loan_data_string[:,:1]

array([['May-15'],
       [''],
       ['Sep-15'],
       ...,
       ['Jun-15'],
       ['Apr-15'],
       ['Dec-15']], dtype='<U69')

In [397]:
np.unique(loan_data_string[:,:1])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [398]:
loan_data_string[:,:1] = np.sort(np.chararray.strip(loan_data_string[:,:1],"-15"))

In [399]:
months = np.unique(np.sort(np.chararray.strip(loan_data_string[:,:1],"-15").squeeze()))

In [400]:
for i in range(13):
  loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i] ,
                                    i , 
                                    loan_data_string[:,0])


In [401]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

**loan_status**

GOOD  'Charged Off' , 'Default','Late (16-30 days)'
==1



BAD  'Current' ,  'Fully Paid', 'In Grace Period', 'Issued',  'Late (31-120 days)'
==0


In [402]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [403]:
status_bad = np.array(['','Charged Off' , 'Default','Late (16-30 days)'])

In [404]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1],status_bad),0,1)

In [405]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

**term_months**

In [406]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [407]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2],'months ')

In [408]:
str_header[2] = "term_months"

**sub_grade**

In [409]:
str_header

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [410]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [411]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [412]:
for i in np.unique(loan_data_string[:,3])[1:]:
  loan_data_string[:,4] = np.where( (loan_data_string[:,4]=='') & (loan_data_string[:,3]==i),
                                   i + '5' ,
                                   loan_data_string[:,4])

In [413]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [414]:
for i in np.unique(loan_data_string[:,3])[1:]:
  loan_data_string[:,4] = np.where( (loan_data_string[:,4]==''),
                                   'H1',
                                   loan_data_string[:,4])

In [415]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

In [416]:
loan_data_string = np.delete( loan_data_string , 3 , axis = 1)

In [417]:
str_header = np.delete(str_header, 3 )

In [418]:
loan_data_string

array([['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['12', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['7', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['1', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['3', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [419]:
str_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [420]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([ 500, 2673, 4116, 2711]))

In [421]:
keys  = list(np.unique(loan_data_string[:,3]))
#keys

In [422]:
values = list(range(1,np.unique(loan_data_string[:,3]).shape[0]+1))
#values

In [423]:
dict_sub_grade = dict(zip(keys,values))
#dict_sub_grade

In [424]:
for i in np.unique(loan_data_string[:,3]):
  loan_data_string[:,3] = np.where(loan_data_string[:,3] == i ,
                                   dict_sub_grade[i],
                                   loan_data_string[:,3])

In [425]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [426]:
loan_data_string[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

In [427]:
loan_data_string[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

**verification_status**

'', 'Not Verified'  ----> 0
'Source Verified', 'Verified' ----->1

In [428]:
str_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [429]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [430]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '')|(loan_data_string[:,4] =='Not Verified'), 0 ,1)

In [431]:
loan_data_string[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

**URL**

In [432]:
loan_data_string[:1,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226'], dtype='<U69')

In [433]:
loan_data_string[:,5] = np.chararray.strip( loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [434]:
loan_data_string[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [435]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

 id and url is as same as each other

In [436]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [437]:
loan_data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [438]:
str_header = np.delete(str_header,5)

In [439]:
loan_data_string = np.delete(loan_data_string,5,axis=1)

**addr_state**

In [440]:
str_header[5]

'addr_state'

50 states in america

In [441]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [442]:
np.unique(loan_data_string[:,5]).shape

(50,)

In [443]:
loan_data_string[:,5] = np.where(loan_data_string[:,5]=='',
                                 0,
                                 loan_data_string[:,5])

In [444]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [445]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), 4, loan_data_string[:,5])

In [446]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

change all data to int

In [447]:
print(loan_data_string)

[['9' '1' '36' '13' '1' '1']
 ['0' '1' '36' '5' '1' '4']
 ['12' '1' '36' '10' '1' '4']
 ...
 ['7' '1' '36' '5' '1' '1']
 ['1' '1' '36' '17' '1' '3']
 ['3' '1' '36' '4' '0' '3']]


In [448]:
#numpy.ndarray
loan_data_string 

array([['9', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['12', '1', '36', '10', '1', '4'],
       ...,
       ['7', '1', '36', '5', '1', '1'],
       ['1', '1', '36', '17', '1', '3'],
       ['3', '1', '36', '4', '0', '3']], dtype='<U69')

In [449]:
type(raw_data_np)

numpy.ndarray

In [450]:
type(loan_data_string)

numpy.ndarray

In [451]:
np.isnan(raw_data_np).sum()

88005

In [452]:
import pandas as pd

# Assuming 'loan_data_string' is a pandas DataFrame
loan_data_string = pd.DataFrame(loan_data_string)

# Check for NaN values in the DataFrame
nan_count = loan_data_string.isnull().sum()

print("Number of NaN values:", nan_count)

Number of NaN values: 0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64


In [453]:
type(loan_data_string[1])


pandas.core.series.Series

In [454]:
type(loan_data_string)

pandas.core.frame.DataFrame

In [455]:
loan_data_string = loan_data_string.to_numpy()

In [456]:
type(loan_data_string[:,1])

numpy.ndarray

In [457]:
loan_data_string

array([['9', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['12', '1', '36', '10', '1', '4'],
       ...,
       ['7', '1', '36', '5', '1', '1'],
       ['1', '1', '36', '17', '1', '3'],
       ['3', '1', '36', '4', '0', '3']], dtype=object)

In [458]:
checkpoint_string = checkpoint("checkpoint_test",str_header, loan_data_string)

In [459]:
checkpoint_string

In [460]:
checkpoint_string["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [465]:
np.isnan(loan_data_num).sum()

8005

In [474]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [475]:
temporary_fill = np.nanmax(raw_data_np) + 1
temporary_mean = np.nanmean(raw_data_np, axis = 0)

<ipython-input-475-eeff3b704aa1>:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis = 0)


In [472]:
loan_data_num[:,0]

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [476]:
temporary_fill

68616520.0

In [477]:
np.isin(loan_data_num[:,0],temporary_fill)

array([False, False, False, ..., False, False, False])

In [478]:
loan_data_num[:,1]

array([35000., 30000., 15000., ..., 10000.,    nan, 10000.])

max/min/max/max/max

In [486]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
                           temporary_mean,
                           np.nanmax(raw_data_np, axis = 0)])

<ipython-input-486-f918bd68decf>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis = 0),
<ipython-input-486-f918bd68decf>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis = 0)])


In [488]:
columns_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
columns_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [489]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

In [490]:
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [494]:
loan_data_num[:,2] = np.where( loan_data_num[:,2] == temporary_fill,
                             temporary_stats[0,columns_numeric[2]],
                             loan_data_num[:,2])
loan_data_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [497]:
loan_data_num[:,3]

array([13.33,   nan,   nan, ...,   nan, 16.55,   nan])

In [498]:
temporary_stats[0,columns_numeric[3]]

6.0

In [499]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [511]:
for i in [1,3,4,5]:
    loan_data_num[:,i] = np.where(loan_data_num[:,i] == temporary_fill,
                                      temporary_stats[2, columns_numeric[i]],
                                      loan_data_num[:,i])

In [512]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,         nan,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,         nan,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,         nan,         nan,     2185.64],
       [46154151.  ,         nan,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,         nan,      309.97,      301.9 ]])

In [513]:
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

**currency**

In [515]:
eur_usd = np.loadtxt("/content/sample_data/EUR-USD.csv" ,
                     delimiter="," , 
                     dtype = np.str_)

In [516]:
eur_usd

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [519]:
eur_usd = np.genfromtxt("/content/sample_data/EUR-USD.csv" ,
                     delimiter="," , 
                     skip_header = 1,
                     autostrip = True,
                     usecols = 3)
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [520]:
loan_data_string[:,0]

array(['9', '0', '12', ..., '7', '1', '3'], dtype=object)

In [550]:
exchange_rate = loan_data_string[:,0]
exchange_rate = exchange_rate.astype(np.int)


<ipython-input-550-0e449ff54337>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  exchange_rate = exchange_rate.astype(np.int)


In [551]:
exchange_rate

array([ 9,  0, 12, ...,  7,  1,  3])

In [552]:
for i in range(1,13):
  exchange_rate = np.where(exchange_rate == i,
                           eur_usd[i-1],
                           exchange_rate)


exchange_rate = np.where(exchange_rate == 0,
                         np.mean(eur_usd),
                         exchange_rate)      

In [553]:
exchange_rate

array([1.13, 1.11, 1.09, ..., 1.09, 1.13, 1.08])

In [554]:
exchange_rate.shape

(10000,)

In [555]:
loan_data_num.shape

(10000, 6)

In [556]:
exchange_rate = np.reshape(exchange_rate,(10000,1))

In [559]:
loan_data_num = np.hstack([loan_data_num,exchange_rate])

In [563]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [566]:
num_header = np.concatenate((num_header,np.array(['exchange_rate'])))
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [567]:
cols_dollar = np.array([1,2,4,5])

In [568]:
loan_data_num[:,cols_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,      nan,  2185.64],
       [     nan, 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [569]:
loan_data_num[:,6]

array([1.13, 1.11, 1.09, ..., 1.09, 1.13, 1.08])

In [570]:
for i in cols_dollar:
    loan_data_num = np.hstack((loan_data_num, np.reshape(loan_data_num[:,i] / loan_data_num[:,6], (10000,1))))

In [571]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31094.7 ,     1052.65,     8398.2 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13718.7 ,      452.59,     1801.57],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9141.4 ,         nan,     1997.98],
       [46154151.  ,         nan,    10000.  , ...,     8859.  ,      313.87,     2834.35],
       [66055249.  ,    10000.  ,    10000.  , ...,     9233.4 ,      286.21,      278.76]])

In [575]:
header_additional = np.array([column_name + '_EUR' for column_name in num_header[cols_dollar]])

In [576]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [579]:
num_header = np.concatenate((num_header,header_additional))

In [580]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [582]:
num_header[cols_dollar] = np.array([column_name + '_USD' for column_name in num_header[cols_dollar]])

In [583]:
num_header

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [584]:
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31094.7 ,     1052.65,     8398.2 ],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13718.7 ,      452.59,     1801.57],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     9141.4 ,         nan,     1997.98],
       [46154151.  ,         nan,    10000.  , ...,     8859.  ,      313.87,     2834.35],
       [66055249.  ,    10000.  ,    10000.  , ...,     9233.4 ,      286.21,      278.76]])

In [587]:
columns_index = [0,1,7,2,8,3,4,9,5,10,6]

In [588]:
num_header = num_header[columns_index]

In [589]:
num_header

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [591]:
loan_data_num[:,5] = loan_data_num[:,5]/100

In [592]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", num_header, loan_data_num)

In [593]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    35000.  , ...,    31094.7 ,     1052.65,     8398.2 ],
        [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
        [59432726.  ,    15000.  ,    15000.  , ...,    13718.7 ,      452.59,     1801.57],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,     9141.4 ,         nan,     1997.98],
        [46154151.  ,         nan,    10000.  , ...,     8859.  ,      313.87,     2834.35],
        [66055249.  ,    10000.  ,    10000.  , ...,     9233.4 ,      286.21,      278.76]]))

In [598]:
loan_data_num.shape

(10000, 11)

In [599]:
loan_data_string.shape

(10000, 6)

In [608]:
all_loan_data = np.hstack((loan_data_num,loan_data_string))

In [607]:
all_header = np.hstack((num_header,str_header))

In [611]:
all_loan_data

array([[48010226.0, 35000.0, 35000.0, ..., '13', '1', '1'],
       [57693261.0, 30000.0, 30000.0, ..., '5', '1', '4'],
       [59432726.0, 15000.0, 15000.0, ..., '10', '1', '4'],
       ...,
       [50415990.0, 10000.0, 10000.0, ..., '5', '1', '1'],
       [46154151.0, nan, 10000.0, ..., '17', '1', '3'],
       [66055249.0, 10000.0, 10000.0, ..., '4', '0', '3']], dtype=object)

In [612]:
all_header

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [613]:
type(all_loan_data)

numpy.ndarray

In [614]:
all_loan_data.shape

(10000, 17)

In [615]:
type(all_header)

numpy.ndarray

In [616]:
all_header.shape

(17,)

In [617]:
all_loan_data = all_loan_data[np.argsort(all_loan_data[:,0])]

In [618]:
all_loan_data

array([[373332.0, 9950.0, nan, ..., '21', '0', '1'],
       [575239.0, 12000.0, 12000.0, ..., '25', '1', '2'],
       [707689.0, 10000.0, 10000.0, ..., '13', '1', '0'],
       ...,
       [68614880.0, 5600.0, 5600.0, ..., '8', '1', '1'],
       [68615915.0, 4000.0, 4000.0, ..., '10', '1', '2'],
       [68616519.0, 21600.0, 21600.0, ..., '3', '0', '2']], dtype=object)

In [619]:
loan_data = np.vstack((all_header, all_loan_data))

In [620]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'addr_state'],
       [373332.0, 9950.0, nan, ..., '21', '0', '1'],
       [575239.0, 12000.0, 12000.0, ..., '25', '1', '2'],
       ...,
       [68614880.0, 5600.0, 5600.0, ..., '8', '1', '1'],
       [68615915.0, 4000.0, 4000.0, ..., '10', '1', '2'],
       [68616519.0, 21600.0, 21600.0, ..., '3', '0', '2']], dtype=object)

In [621]:
np.savetxt("loan-data-preprocessed.csv", 
           loan_data, 
           fmt = '%s',
           delimiter = ',')