<a href="https://colab.research.google.com/github/faeezeh/Numpy/blob/main/NumpyEx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy exercise**

1. Every categorical variable must be quantified

2. We need to change any text columns into numbers

3. Positive or negative connotation 

In [249]:
import numpy as np 

In [250]:
np.set_printoptions( suppress = True , linewidth = 100 , precision = 2 )

In [251]:
raw_data_np = np.genfromtxt("/content/sample_data/loan-data.csv",
                            delimiter=";",
                            skip_header=1,
                            autostrip=True,
                            encoding="cp855")
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [252]:
np.isnan(raw_data_np).sum()

88005

In [253]:
temp_mean =  np.nanmean(raw_data_np , axis=0)
temp_min =  np.nanmin(raw_data_np , axis=0)
temp_fill = np.nanmax(raw_data_np) + 1

<ipython-input-253-d8c71dda0048>:1: RuntimeWarning: Mean of empty slice
  temp_mean =  np.nanmean(raw_data_np , axis=0)
<ipython-input-253-d8c71dda0048>:2: RuntimeWarning: All-NaN slice encountered
  temp_min =  np.nanmin(raw_data_np , axis=0)


In [254]:
temp_min

array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
             nan,       nan,       nan,       nan,       nan,      0.  ])

In [255]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [256]:
temp_fill

68616520.0

In [257]:
temp_sets = np.array([temp_min,temp_mean,temp_fill])

<ipython-input-257-10f5c992cf5e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  temp_sets = np.array([temp_min,temp_mean,temp_fill])


In [258]:
temp_sets

array([array([373332.  ,       nan,   1000.  ,       nan,   1000.  ,       nan,      6.  ,     31.42,
                    nan,       nan,       nan,       nan,       nan,      0.  ])                     ,
       array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
                   440.92,         nan,         nan,         nan,         nan,         nan,     3143.85]),
       68616520.0], dtype=object)

In [259]:
cols_string = np.argwhere(np.isnan(temp_mean)).squeeze()
cols_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [260]:
cols_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
cols_numeric

array([ 0,  2,  4,  6,  7, 13])

In [261]:
loan_data_string = np.genfromtxt("/content/sample_data/loan-data.csv",
                            delimiter=";",
                            skip_header=1,
                            autostrip=True,
                            usecols = cols_string,
                            encoding="cp855",
                            dtype = np.str)
loan_data_string

<ipython-input-261-72b7ab78f43f>:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [262]:
loan_data_num = np.genfromtxt("/content/sample_data/loan-data.csv",
                            delimiter=";",
                            skip_header=1,
                            autostrip=True,
                            usecols = cols_numeric,
                            encoding="cp855")
loan_data_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,         nan,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,         nan,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,         nan,         nan,     2185.64],
       [46154151.  ,         nan,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,         nan,      309.97,      301.9 ]])

In [263]:
header = np.genfromtxt("/content/sample_data/loan-data.csv",
                             delimiter=";",
                            skip_footer=raw_data_np.shape[0],
                            autostrip=True,
                            encoding="cp855",
                            dtype = np.str)
header

<ipython-input-263-20add4c119f6>:6: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [264]:
str_header , num_header = header[cols_string],header[cols_numeric]

In [265]:
str_header

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [266]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [267]:
def checkpoint ( file_name , checkpoint_header , checkpoint_data):
  np.savez( file_name , header = checkpoint_header , data = checkpoint_data )
  checkpoint_variable = np.load( file_name + ".npz" )
  return(checkpoint_variable)

In [268]:
checkpoint_test = checkpoint("checkpoint_test",str_header, loan_data_string)

In [269]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [270]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [271]:
str_header[0] = "issue_date"

In [272]:
str_header

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

**issue_date**

In [273]:
loan_data_string[:,:1]

array([['May-15'],
       [''],
       ['Sep-15'],
       ...,
       ['Jun-15'],
       ['Apr-15'],
       ['Dec-15']], dtype='<U69')

In [274]:
np.unique(loan_data_string[:,:1])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [275]:
loan_data_string[:,:1] = np.sort(np.chararray.strip(loan_data_string[:,:1],"-15"))

In [276]:
months = np.unique(np.sort(np.chararray.strip(loan_data_string[:,:1],"-15").squeeze()))

In [277]:
for i in range(13):
  loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i] ,
                                    i , 
                                    loan_data_string[:,0])


In [278]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

**loan_status**

GOOD  'Charged Off' , 'Default','Late (16-30 days)'
==1



BAD  'Current' ,  'Fully Paid', 'In Grace Period', 'Issued',  'Late (31-120 days)'
==0


In [279]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [280]:
status_bad = np.array(['','Charged Off' , 'Default','Late (16-30 days)'])

In [281]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1],status_bad),0,1)

In [282]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

**term_months**

In [283]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [284]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2],'months ')

In [285]:
str_header[2] = "term_months"

**sub_grade**

In [286]:
str_header

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [287]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [288]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [289]:
for i in np.unique(loan_data_string[:,3])[1:]:
  loan_data_string[:,4] = np.where( (loan_data_string[:,4]=='') & (loan_data_string[:,3]==i),
                                   i + '5' ,
                                   loan_data_string[:,4])

In [290]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [291]:
for i in np.unique(loan_data_string[:,3])[1:]:
  loan_data_string[:,4] = np.where( (loan_data_string[:,4]==''),
                                   'H1',
                                   loan_data_string[:,4])

In [292]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9]))

In [293]:
loan_data_string = np.delete( loan_data_string , 3 , axis = 1)

In [294]:
str_header = np.delete(str_header, 3 )

In [295]:
loan_data_string

array([['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['12', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['7', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['1', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['3', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [296]:
str_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [297]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([ 500, 2673, 4116, 2711]))

In [298]:
keys  = list(np.unique(loan_data_string[:,3]))
#keys

In [299]:
values = list(range(1,np.unique(loan_data_string[:,3]).shape[0]+1))
#values

In [300]:
dict_sub_grade = dict(zip(keys,values))
#dict_sub_grade

In [301]:
for i in np.unique(loan_data_string[:,3]):
  loan_data_string[:,3] = np.where(loan_data_string[:,3] == i ,
                                   dict_sub_grade[i],
                                   loan_data_string[:,3])

In [302]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [303]:
loan_data_string[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69')

In [304]:
loan_data_string[:,1]

array(['1', '1', '1', ..., '1', '1', '1'], dtype='<U69')

**verification_status**

'', 'Not Verified'  ----> 0
'Source Verified', 'Verified' ----->1

In [305]:
str_header

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [306]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [307]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '')|(loan_data_string[:,4] =='Not Verified'), 0 ,1)

In [308]:
loan_data_string[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], dtype='<U69')

**URL**

In [309]:
loan_data_string[:1,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226'], dtype='<U69')

In [310]:
loan_data_string[:,5] = np.chararray.strip( loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [311]:
loan_data_string[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [312]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

 id and url is as same as each other

In [313]:
num_header

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [314]:
loan_data_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [315]:
str_header = np.delete(str_header,5)

In [316]:
loan_data_string = np.delete(loan_data_string,5,axis=1)

**addr_state**

In [317]:
str_header[5]

'addr_state'

50 states in america

In [318]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [319]:
np.unique(loan_data_string[:,5]).shape

(50,)

In [320]:
loan_data_string[:,5] = np.where(loan_data_string[:,5]=='',
                                 0,
                                 loan_data_string[:,5])

In [321]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [322]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), 1, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), 2, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), 3, loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), 4, loan_data_string[:,5])

In [323]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

change all data to int

In [324]:
print(loan_data_string)

[['9' '1' '36' '13' '1' '1']
 ['0' '1' '36' '5' '1' '4']
 ['12' '1' '36' '10' '1' '4']
 ...
 ['7' '1' '36' '5' '1' '1']
 ['1' '1' '36' '17' '1' '3']
 ['3' '1' '36' '4' '0' '3']]


In [325]:
#numpy.ndarray
loan_data_string 

array([['9', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['12', '1', '36', '10', '1', '4'],
       ...,
       ['7', '1', '36', '5', '1', '1'],
       ['1', '1', '36', '17', '1', '3'],
       ['3', '1', '36', '4', '0', '3']], dtype='<U69')

In [329]:
type(raw_data_np)

numpy.ndarray

In [330]:
type(loan_data_string)

numpy.ndarray

In [331]:
np.isnan(raw_data_np).sum()

88005

In [340]:
import pandas as pd

# Assuming 'loan_data_string' is a pandas DataFrame
loan_data_string = pd.DataFrame(loan_data_string)

# Check for NaN values in the DataFrame
nan_count = loan_data_string.isnull().sum()

print("Number of NaN values:", nan_count)

Number of NaN values: 0    0
1    0
2    0
3    0
4    0
5    0
dtype: int64


In [347]:
type(loan_data_string[1])


pandas.core.series.Series

In [336]:
type(loan_data_string)

pandas.core.frame.DataFrame

In [348]:
loan_data_string = loan_data_string.to_numpy()

In [351]:
type(loan_data_string[:,1])

numpy.ndarray

In [353]:
loan_data_string

array([['9', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['12', '1', '36', '10', '1', '4'],
       ...,
       ['7', '1', '36', '5', '1', '1'],
       ['1', '1', '36', '17', '1', '3'],
       ['3', '1', '36', '4', '0', '3']], dtype=object)

In [367]:
checkpoint_string = checkpoint("checkpoint_test",str_header, loan_data_string)

In [368]:
checkpoint_string

In [369]:
checkpoint_string["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')